name: FearForAll
main: com.division.fearforall.core.FearForAll
version: 1.3.3HFB
description: FearForAll region system
commands:
   ffa:
      description: Defines ffa region.
      permission: fearforall.ffa
      usage: /ffa define
authors: [Mastershake71]
depend: [Vault, Factions]